version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    container_name: file_storage_postgres
    environment:
      POSTGRES_DB: file_storage_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  backend:
    container_name: file_storage_backend
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./migrations:/src/migrations:rw
