version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    container_name: file_storage_postgres
    environment:
      POSTGRES_DB: file_storage_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - ./postgres_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  backend:
    container_name: file_storage_backend
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    expose:
      - 8000
    volumes:
      - ./migrations:/src/migrations:rw
      - ./app:/src/app:rw

    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --workers 1"

  nginx:
    image: nginx:1.19.2
    container_name: file_storage_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - "80:80"