version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    container_name: file_storage_postgres
    environment:
      POSTGRES_DB: file_storage_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
        - ./postgres_data:/var/lib/postgresql/data

  backend:
    container_name: file_storage_backend
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./migrations:/src/migrations:rw
      - ./app:/src/app:rw


  nginx:
    image: nginx:1.25.2
    container_name: file_storage_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    ports:
      - "80:80"